sudo: false

language: android
jdk: oraclejdk8

android:
  components:
  - tools # to get the new `repository-11.xml`
  - platform-tools
  - tools # to install newer Android SDK tools
  - build-tools-27.0.3
  - android-22 # Android platform used by your alternative emulator
  - android-27
  - sys-img-armeabi-v7a-android-22

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

before_install:
- chmod +x gradlew
# workaround for travis bug
- yes | sdkmanager "platforms;android-27"

# Emulator Management: Create, Start and Wait
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
- "./gradlew clean lint connectedAndroidTest -PdisablePreDex --stacktrace"

notifications:
  email: true

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
