sudo: false

language: android
jdk: oraclejdk8

notifications:
  email: true

env:
  global:
   # install timeout in minutes (2 minutes by default)
  - ADB_INSTALL_TIMEOUT=8

android:
  components:
  - tools # to get the new `repository-11.xml`
  - platform-tools
  - tools # to install newer Android SDK tools
  - build-tools-27.0.3
  - android-22 # Android platform used by your alternative emulator
  - android-27
  - sys-img-armeabi-v7a-android-22

before_install:
# decrypt the signing key
- openssl aes-256-cbc -K $encrypted_7915ebf78935_key -iv $encrypted_7915ebf78935_iv -in keystoreAdbClipboard.enc -out keystoreAdbClipboard -d
- chmod +x gradlew
# workaround for travis bug
- yes | sdkmanager "platforms;android-27"

# Emulator Management: create, start and wait
- android list targets
- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

script:
- "./gradlew clean build check connectedCheck -PdisablePreDex --stacktrace"

deploy:
  provider: releases
  file_glob: true
  file: "app/build/outputs/apk/release/AdbClipboard-*.apk"
  skip_cleanup: true
  on:
    repo: PRosenb/AdbClipboard
    tags: true
  api_key:
    secure: h5YOaqMClPuPWUMb05IoOJn1OxCW8Pg5EkUK3ZBwrx62WbxEVPution9js2tHo3DTmvvTNWDAFRYYtGqwM4M9LYGwnmeAs5Mi2qvw6nBB8cAUPKqT1aHlGB+4xCbIbjKMtsHFgPSHqjjMqqY+mIbwKQdNTobuUoHtccwpPhCIkCLNrW/a3M0XOKkEj4AAa76UANB8p1XqKQVPC/EGNcRBBnTUuSVOSMR76kmklsXdiSUBw9vr35DBYJAdnGMmYt9f9fGySLP+88vi/PdZgaqSG7YSKTcKCH5J1CcETIltHhMXLDSzFqkEZ93x2EiZVQGd7YqOgP9OHePv/oQdcsOzXKZ+X90p57iC+ydQxOfB1E7jGTaneRBY8wWwlJjdnDx81N7Uq6nDQFKIWYmRHtQBCum4ma7ZLqCWR4H1v5BehU1rFMNdCAhqQ+S9YX2n3cnraXv7Sm1Ql1r1UDMqZAb6Z6K2lo2o/9EdzfnACYhua/g4noh+XUNzgYWJLSB+5mvhUbC3TUyN4p9CM0T6OQ4oSClUPzLn13nH8SWiivqckANksYR4Ds8eaIV9nc//JL4mVBppi/92NKJ0o/GmctXBDyuVpvnSPrmWwjxcskWwAmWSMEX3yMjCh65onZa1ZqK1FTPyVCQxvlSuiLJkeG0bBE7NG5pzmrUEtC4vfHe1Wk=

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
